### ISSUE TITLE
Do you consider the mask problem for attention?

### ISSUE THREAD

**Issue by gaopengcuhk** [gicheonkang/DAN-VisDial#4]

**Comment by gicheonkang** [comment]
Thank you for your interests in our work. 
First, It is not clear that the attention you mentioned is REFER module or FIND module.
In REFER module, we don't need to consider the mask because we just make the REFER module compute the multi-head attention between the question and dialog history.
In FIND module, we also didn't employ the mask in our published work. But, we newly implemented the visual mask for the researchers who will reuse this code. You can check the details in [encoders/modules.py file](https://github.com/gicheonkang/DAN-VisDial/blob/master/encoders/modules.py).
